### ISSUE TITLE
react-application-tenant-global-navbar build fails at deasync@0.1.10

### ISSUE THREAD

**Issue by kayodebristol** [SharePoint/sp-dev-fx-extensions#182]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior
Success

## Observed Behavior

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  deasync.cc
  win_delay_load_hook.cc
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\nan\nan_maybe_43_inl.h(112): error C203 9: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\r eact-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
 gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.10 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Steps to Reproduce

Initial error stated the build tools could not be found. Fix for that, below:
npm install --global --production windows-build-tools
npm config set msvs_version 2017 --global

---
cd \sp-dev-fx-extensions\samples\react-application-tenant-global-navbar
npm install 

[Bam! Error message as stated above]

**Comment by kayodebristol** [comment]
Installing and using yarn seems to resolve this.
