### ISSUE TITLE
Unmodified sample code fails with TypeScript errors

### ISSUE THREAD

**Issue by pensphreak** [SharePoint/sp-dev-fx-extensions#301]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement
- [ ] Sample request

## Expected or Desired Behavior

Running the sample extension react-application-breadcrumb without failing

## Observed Behavior

When I ran it from my work PC, it failed like the code below.  I did same thing on my home PC and it worked fine.  So I copied the entire folder (node_modules and all) from my working PC to my work PC and it still failed.  So there must be something in my environment that's causing this.  So I completely uninstalled and reinstalled node v10 and it still failed (tried node v8 as well)

PS C:\Projects\spfx\react-application-breadcrumb> gulp serve-info --nobrowser
Build target: DEBUG
[07:51:20] Using gulpfile C:\Projects\spfx\react-application-breadcrumb\gulpfile.js
[07:51:20] Starting gulp
[07:51:20] Starting 'serve'...
[07:51:20] Starting subtask 'configure-sp-build-rig'...
[07:51:20] Finished subtask 'configure-sp-build-rig' after 5.55 ms
[07:51:20] Starting subtask 'spfx-serve'...
[07:51:20] Warning - [spfx-serve] When serving in HTTPS mode, a PFX cert path or a cert path and a key path must be provided, or a dev certificate must be generated and trusted. If a SSL certificate isn't provided, a def
ault, self-signed certificate will be used. Expect browser security warnings.
Starting api server on port 5432.
Registring api: /getwebparts
Registring api: /*.*
Registring api: /workbench
[07:51:20] Finished subtask 'spfx-serve' after 378 ms
[07:51:20] Starting subtask 'pre-copy'...
[07:51:20] Finished subtask 'pre-copy' after 7.37 ms
[07:51:20] Starting subtask 'copy-static-assets'...
[07:51:20] Starting subtask 'sass'...
[07:51:21] Server started https://localhost:4321
[07:51:21] LiveReload started on port 35729
[07:51:21] Finished subtask 'sass' after 727 ms
[07:51:21] Starting subtask 'tslint'...
[07:51:22] Starting subtask 'typescript'...
[07:51:22] [typescript] TypeScript version: 2.4.2
[07:51:22] Finished subtask 'copy-static-assets' after 1.7 s

Could not find implementations for the following rules specified in the configuration:
    no-unused-imports
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

Warning: no-duplicate-case rule is deprecated. Replace your usage with the TSLint no-duplicate-switch-case rule.
Warning: valid-typeof rule is deprecated. Replace your usage with the TSLint typeof-compare rule.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(31,37): error TS1005: '=' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(33,38): error TS1005: ';' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,46): error TS1005: ';' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,47): error TS1109: Expression expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,48): error TS1109: Expression expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,75): error TS1109: Expression expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,99): error TS1005: ';' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,102): error TS1109: Expression expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,118): error TS1109: Expression expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,143): error TS1005: ';' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,151): error TS1128: Declaration or statement expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,159): error TS1005: ',' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(37,49): error TS1005: ';' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(37,50): error TS1109: Expression expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(37,51): error TS1109: Expression expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(37,68): error TS1005: '(' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(37,70): error TS1128: Declaration or statement expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(52,29): error TS1005: ';' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(52,53): error TS1005: ';' expected.
[07:51:23] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(52,56): error TS1109: Expression expected.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(31,30): error TS2304: Cannot find name 'unique'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(33,46): error TS2304: Cannot find name 'T'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,50): error TS2304: Cannot find name 'Exclude'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,58): error TS2304: Cannot find name 'V'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,60): error TS2304: Cannot find name 'K'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,64): error TS2532: Object is possibly 'undefined'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,83): error TS2693: 'Validator' only refers to a type, but is being used as a value here.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,93): error TS2304: Cannot find name 'infer'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,99): error TS2304: Cannot find name 'T'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,104): error TS2693: 'IsOptional' only refers to a type, but is being used as a value here.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,115): error TS2304: Cannot find name 'T'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,133): error TS2693: 'never' only refers to a type, but is being used as a value here.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,141): error TS2304: Cannot find name 'K'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,145): error TS2693: 'never' only refers to a type, but is being used as a value here.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,153): error TS2304: Cannot find name 'keyof'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(35,159): error TS2304: Cannot find name 'V'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(36,30): error TS2304: Cannot find name 'Exclude'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(37,53): error TS2693: 'InferType' only refers to a type, but is being used as a value here.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(37,63): error TS2304: Cannot find name 'V'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(37,65): error TS2304: Cannot find name 'K'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(47,26): error TS2304: Cannot find name 'NonNullable'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(52,37): error TS2693: 'Validator' only refers to a type, but is being used as a value here.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(52,47): error TS2304: Cannot find name 'infer'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(52,53): error TS2304: Cannot find name 'T'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(52,58): error TS2304: Cannot find name 'T'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(54,30): error TS2344: Type 'RequiredKeys<V>' does not satisfy the constraint 'keyof V'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(70,77): error TS2304: Cannot find name 'NonNullable'.
[07:51:24] Error - typescript - ..\node_modules\@types\prop-types\index.d.ts(74,74): error TS2304: Cannot find name 'Required'.
[07:51:24] Finished subtask 'tslint' after 3.53 s
[07:51:24] Error - 'typescript' sub task errored after 2.6 s
 TypeScript error(s) occurred.
(node:4600) UnhandledPromiseRejectionWarning: TypeError: options.message.replace is not a function
    at Object.module.exports.mapToWin8 (C:\Projects\spfx\react-application-breadcrumb\node_modules\node-notifier\lib\utils.js:359:33)
    at WindowsToaster.notify (C:\Projects\spfx\react-application-breadcrumb\node_modules\node-notifier\notifiers\toaster.js:88:19)
    at C:\Projects\spfx\react-application-breadcrumb\node_modules\@microsoft\gulp-core-build\lib\index.js:213:46
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with
.catch(). (rejection id: 10)
(node:4600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to Reproduce

npm install
gulp serve-info --nobrowser

**Comment by pensphreak** [comment]
It appears that I had some leftover / misplaced stuff in a directory up one level (hence the ..\node_modules\....). Once I removed that node_modules directory, everything worked just fine
